theme = "autumn_night"

[editor]
auto-pairs = false
line-number = "relative"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.whitespace.characters]
newline = "⏎"

[keys.normal]
C-S-d = [":insert-output date +'%a, %d.%m.%Y'"]
