[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright.analysis]
autoImportCompletions = true

#[language-server.pylsp]
#command = "pylsp"
#plugins.rope_autoimport.enabled = true
#plugins.rope_autoimport.code_actions.enabled = true
#plugins.rope_autoimport.completions.enabled = true

[[language]]
name = "python"
scope = "source.python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language-server.pylsp.config.pylsp.plugins]
pylsp_mypy.enabled = true
pylsp_mypy.live_mode = true
rope_autoimport.enabled = true

[[language]]
name = "rust"
auto-format = true

